# Generated by Django 2.1.7 on 2019-03-09 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('design_title', models.CharField(max_length=225, verbose_name='A/B Testing Title')),
                ('design_image_a', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('design_image_b', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('design_comment', models.TextField(verbose_name='Comment')),
                ('design_password', models.CharField(max_length=128, verbose_name='Design Page Password')),
                ('is_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_modified', models.DateTimeField(auto_now=True, null=True)),
                ('design_tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_forums', to='app_user.Tester')),
            ],
        ),
    ]
