# Generated by Django 2.1.7 on 2019-03-14 06:51

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('app_user', '0002_auto_20190314_1351'),
        ('app_abtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_abtest_tester_name', models.CharField(default='Tester', max_length=225, verbose_name='Tester name')),
                ('design_abtest_choice', models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=1, null=True, verbose_name='A/B?')),
                ('design_abtest_comment', models.TextField(verbose_name='Comment')),
                ('is_published', models.BooleanField(default=False)),
                ('is_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_modified', models.DateTimeField(auto_now=True, null=True)),
                ('design_abtest_tester_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tester_user_hook', to='app_user.Tester', verbose_name='Tester user')),
            ],
            options={
                'verbose_name_plural': 'Test Results',
            },
        ),
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name_plural': 'Design Testing Materials'},
        ),
        migrations.RemoveField(
            model_name='design',
            name='design_comment',
        ),
        migrations.RemoveField(
            model_name='design',
            name='design_password',
        ),
        migrations.RemoveField(
            model_name='design',
            name='design_tester',
        ),
        migrations.AddField(
            model_name='design',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='design',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='designcomment',
            name='design_abtest_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_title', to='app_abtest.Design', verbose_name='Testing Title'),
        ),
    ]
