# Generated by Django 2.1.7 on 2019-03-14 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0002_auto_20190314_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcomment',
            name='design_abtest_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testing_title', to='app_abtest.Design', verbose_name='Testing Title'),
        ),
    ]
