# Generated by Django 2.1.7 on 2019-03-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
        ('app_abtest', '0003_remove_design_design_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='design_tester',
        ),
        migrations.AddField(
            model_name='design',
            name='design_tester_name',
            field=models.CharField(default='Tester', max_length=225, verbose_name='Terter name'),
        ),
        migrations.AddField(
            model_name='design',
            name='design_tester_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_forums', to='app_user.Tester', verbose_name='Terter user'),
        ),
    ]
