# Generated by Django 2.1.7 on 2019-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0004_auto_20190311_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
