# Generated by Django 2.1.7 on 2019-03-12 06:35

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('app_abtest', '0005_design_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
