# Generated by Django 2.1.7 on 2019-03-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
        ('app_abtest', '0006_design_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_abtest_tester_name', models.CharField(default='Tester', max_length=225, verbose_name='Tester name')),
                ('design_abtest_comment', models.TextField(verbose_name='Comment')),
                ('is_published', models.BooleanField(default=False)),
                ('is_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_modified', models.DateTimeField(auto_now=True, null=True)),
                ('design_abtest_tester_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_forums', to='app_user.Tester', verbose_name='Tester user')),
            ],
        ),
        migrations.RemoveField(
            model_name='design',
            name='design_comment',
        ),
        migrations.RemoveField(
            model_name='design',
            name='design_tester_name',
        ),
        migrations.RemoveField(
            model_name='design',
            name='design_tester_user',
        ),
        migrations.AddField(
            model_name='designcomment',
            name='design_abtest_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abtest.Design'),
        ),
    ]
