# Generated by Django 2.1.7 on 2019-03-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0006_auto_20190314_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcomment',
            name='design_abtest_tester_phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='No handphone'),
        ),
        migrations.AlterField(
            model_name='designcomment',
            name='design_abtest_choice',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=1, null=True, verbose_name='Pilih A/B?'),
        ),
        migrations.AlterField(
            model_name='designcomment',
            name='design_abtest_comment',
            field=models.TextField(verbose_name='Komentar'),
        ),
        migrations.AlterField(
            model_name='designcomment',
            name='design_abtest_tester_name',
            field=models.CharField(default='Tester', max_length=225, verbose_name='Nama'),
        ),
    ]
