# Generated by Django 2.1.7 on 2019-03-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0007_auto_20190316_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='designcomment',
            name='design_abtest_tester_email',
            field=models.EmailField(blank=True, max_length=225, null=True, verbose_name='Email'),
        ),
    ]
