# Generated by Django 2.1.7 on 2019-03-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0007_auto_20190312_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcomment',
            name='design_abtest_tester_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tester', to='app_user.Tester', verbose_name='Tester user'),
        ),
        migrations.AlterField(
            model_name='designcomment',
            name='design_abtest_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_abtest.Design', verbose_name='Testing Title'),
        ),
    ]
