# Generated by Django 2.1.7 on 2019-03-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0008_designcomment_design_abtest_tester_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcomment',
            name='design_abtest_tester_email',
            field=models.ForeignKey(blank=True, max_length=225, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.Tester', verbose_name='Email'),
        ),
    ]
