# Generated by Django 2.1.7 on 2019-03-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0010_auto_20190320_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designcomment',
            name='design_abtest_tester_name',
        ),
        migrations.RemoveField(
            model_name='designcomment',
            name='design_abtest_tester_phone',
        ),
    ]
