# Generated by Django 2.1.7 on 2019-03-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0011_auto_20190322_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcomment',
            name='design_abtest_choice',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B')], default='a', max_length=1, verbose_name='Pilih A/B?'),
            preserve_default=False,
        ),
    ]
