# Generated by Django 2.1.7 on 2019-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0014_auto_20190326_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designcomment',
            name='design_abtest_comment',
            field=models.TextField(help_text='Kenapa kamu memilih pilihan itu? Bisa coba tolong jelaskan? <b>Minimal 30 karakter</b>', verbose_name='Komentar'),
        ),
    ]
