# Generated by Django 2.1.7 on 2019-03-26 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0016_auto_20190326_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
