# Generated by Django 2.1.7 on 2019-03-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0017_auto_20190326_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
