# Generated by Django 2.1.7 on 2019-03-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_abtest', '0019_auto_20190326_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
